version: "3.8"

services:
  krakend:
    image: devopsfaith/krakend:2.7
    command: ["run", "-c", "/etc/krakend/krakend.json"]
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json:ro
    networks:
      - default
    ports:
      - target: 8080
        published: 8089
        protocol: tcp
        mode: host

networks:
  default:
    external: true
    name: overlay-swarm